### ISSUE TITLE
Usage sample?

### ISSUE THREAD

**Issue by randohinn** [Voog/dragdrop.js#1]
Hey,

Is there a usage sample for this? the demo seems to not work, even with jQuery from the CDN :/ and the lib folder doesn't have droppable.js. Seems OK otherwize.

**Comment by priithaamer** [comment]
Hey, we have plans to release proper documentation in the near future. Until then, feel free to contact me anytime and show us what you are attempting to build. I'd be happy to help you with code samples etc.

**Comment by randohinn** [comment]
@priithaamer Brilliant. Just getting the included demo to work would be a great start.

**Comment by randohinn** [comment]
@priithaamer Have you got anything? I can get around the missing `droppable.js` file, by simply not using the script tag at the bottom of the page, but that doesn't fix all errors. Something has gone bad in `draggable.js`aswell: `Cannot set property 'currentDrags' of undefined`

**Comment by randohinn** [comment]
Over a year... :/

**Comment by priithaamer** [comment]
Thanks for your patience 😄 

However, we have switched to React DND and will not maintain this repository any longer. I'm very sorry this info is not reflected here.

**Comment by randohinn** [comment]
Ok, no problem. I've been liking Dragula in the meantime. But just thought it would be  cool to use a library made in Estonia 😄
